[filters.abs]
fn = "jinja2.filters.abs"
group = "builtin"
[filters.abs.examples.basic]
template = """
{{ -5 | abs }}
"""

[filters.attr]
fn = "jinja2.filters.do_attr"
group = "builtin"
[filters.attr.examples.basic]
template = """
{{ "sth" | attr }}
"""

[filters.batch]
fn = "jinja2.filters.do_batch"
group = "builtin"
[filters.batch.examples.basic]
template = """
{{ "sth" | batch }}
"""

[filters.capitalize]
fn = "jinja2.filters.do_capitalize"
group = "builtin"
[filters.capitalize.examples.basic]
template = """
{{ "sth" | capitalize }}
"""

[filters.center]
fn = "jinja2.filters.do_center"
group = "builtin"
[filters.center.examples.basic]
template = """
{{ "sth" | center }}
"""

[filters.count]
fn = "jinja2.filters.len"
group = "builtin"
[filters.count.examples.basic]
template = """
{{ "sth" | count }}
"""

[filters.default]
fn = "jinja2.filters.do_default"
group = "builtin"
aliases = "d"
[filters.default.examples.basic]
template = """
{{ "sth" | default }}
"""

[filters.dictsort]
fn = "jinja2.filters.do_dictsort"
group = "builtin"
[filters.dictsort.examples.basic]
template = """
{{ "sth" | dictsort }}
"""

[filters.escape]
fn = "jinja2.filters.escape"
group = "builtin"
aliases = ["e"]
[filters.escape.examples.basic]
template = """
{{ "sth" | escape }}
"""

[filters.filesizeformat]
fn = "jinja2.filters.do_filesizeformat"
group = "builtin"
[filters.filesizeformat.examples.basic]
template = """
{{ "sth" | filesizeformat }}
"""

[filters.first]
fn = "jinja2.filters.do_first"
group = "builtin"
[filters.first.examples.basic]
template = """
{{ "sth" | first }}
"""

[filters.float]
fn = "jinja2.filters.do_float"
group = "builtin"
[filters.float.examples.basic]
template = """
{{ "sth" | float }}
"""

[filters.forceescape]
fn = "jinja2.filters.do_forceescape"
group = "builtin"
[filters.forceescape.examples.basic]
template = """
{{ "sth" | forceescape }}
"""

[filters.format]
fn = "jinja2.filters.do_format"
group = "builtin"
[filters.format.examples.basic]
template = """
{{ "sth" | format }}
"""

[filters.groupby]
fn = "jinja2.filters.do_groupby"
group = "builtin"
[filters.groupby.examples.basic]
template = """
{{ "sth" | groupby }}
"""

[filters.indent]
fn = "jinja2.filters.do_indent"
group = "builtin"
[filters.indent.examples.basic]
template = """
{{ "sth" | indent }}
"""

[filters.int]
fn = "jinja2.filters.do_int"
group = "builtin"
[filters.int.examples.basic]
template = """
{{ "sth" | int }}
"""

[filters.join]
fn = "jinja2.filters.do_join"
group = "builtin"
[filters.join.examples.basic]
template = """
{{ "sth" | join }}
"""

[filters.last]
fn = "jinja2.filters.do_last"
group = "builtin"
[filters.last.examples.basic]
template = """
{{ "sth" | last }}
"""

[filters.length]
fn = "jinja2.filters.len"
group = "builtin"
[filters.length.examples.basic]
template = """
{{ "sth" | length }}
"""

[filters.list]
fn = "jinja2.filters.do_list"
group = "builtin"
[filters.list.examples.basic]
template = """
{{ "sth" | list }}
"""

[filters.lower]
fn = "jinja2.filters.do_lower"
group = "builtin"
[filters.lower.examples.basic]
template = """
{{ "sth" | lower }}
"""

[filters.items]
fn = "jinja2.filters.do_items"
group = "builtin"
[filters.items.examples.basic]
template = """
{{ "sth" | items }}
"""

[filters.map]
fn = "jinja2.filters.do_map"
group = "builtin"
[filters.map.examples.basic]
template = """
{{ "sth" | map }}
"""

[filters.min]
fn = "jinja2.filters.do_min"
group = "builtin"
[filters.min.examples.basic]
template = """
{{ "sth" | min }}
"""

[filters.max]
fn = "jinja2.filters.do_max"
group = "builtin"
[filters.max.examples.basic]
template = """
{{ "sth" | max }}
"""

[filters.pprint]
fn = "jinja2.filters.do_pprint"
group = "builtin"
[filters.pprint.examples.basic]
template = """
{{ "sth" | pprint }}
"""

[filters.random]
fn = "jinja2.filters.do_random"
group = "builtin"
[filters.random.examples.basic]
template = """
{{ "sth" | random }}
"""

[filters.reject]
fn = "jinja2.filters.do_reject"
group = "builtin"
[filters.reject.examples.basic]
template = """
{{ "sth" | reject }}
"""

[filters.rejectattr]
fn = "jinja2.filters.do_rejectattr"
group = "builtin"
[filters.rejectattr.examples.basic]
template = """
{{ "sth" | rejectattr }}
"""

[filters.replace]
fn = "jinja2.filters.do_replace"
group = "builtin"
[filters.replace.examples.basic]
template = """
{{ "sth" | replace }}
"""

[filters.reverse]
fn = "jinja2.filters.do_reverse"
group = "builtin"
[filters.reverse.examples.basic]
template = """
{{ "sth" | reverse }}
"""

[filters.round]
fn = "jinja2.filters.do_round"
group = "builtin"
[filters.round.examples.basic]
template = """
{{ "sth" | round }}
"""

[filters.safe]
fn = "jinja2.filters.do_mark_safe"
group = "builtin"
[filters.safe.examples.basic]
template = """
{{ "sth" | safe }}
"""

[filters.select]
fn = "jinja2.filters.do_select"
group = "builtin"
[filters.select.examples.basic]
template = """
{{ "sth" | select }}
"""

[filters.selectattr]
fn = "jinja2.filters.do_selectattr"
group = "builtin"
[filters.selectattr.examples.basic]
template = """
{{ "sth" | selectattr }}
"""

[filters.slice]
fn = "jinja2.filters.do_slice"
group = "builtin"
[filters.slice.examples.basic]
template = """
{{ "sth" | slice }}
"""

[filters.sort]
fn = "jinja2.filters.do_sort"
group = "builtin"
[filters.sort.examples.basic]
template = """
{{ "sth" | sort }}
"""

[filters.string]
fn = "jinja2.filters.soft_str"
group = "builtin"
[filters.string.examples.basic]
template = """
{{ "sth" | string }}
"""

[filters.striptags]
fn = "jinja2.filters.do_striptags"
group = "builtin"
[filters.striptags.examples.basic]
template = """
{{ "sth" | striptags }}
"""

[filters.sum]
fn = "jinja2.filters.do_sum"
group = "builtin"
[filters.sum.examples.basic]
template = """
{{ "sth" | sum }}
"""

[filters.title]
fn = "jinja2.filters.do_title"
group = "builtin"
[filters.title.examples.basic]
template = """
{{ "sth" | title }}
"""

[filters.trim]
fn = "jinja2.filters.do_trim"
group = "builtin"
[filters.trim.examples.basic]
template = """
{{ "sth" | trim }}
"""

[filters.truncate]
fn = "jinja2.filters.do_truncate"
group = "builtin"
[filters.truncate.examples.basic]
template = """
{{ "sth" | truncate }}
"""

[filters.unique]
fn = "jinja2.filters.do_unique"
group = "builtin"
[filters.unique.examples.basic]
template = """
{{ "sth" | unique }}
"""

[filters.upper]
fn = "jinja2.filters.do_upper"
group = "builtin"
[filters.upper.examples.basic]
template = """
{{ "sth" | upper }}
"""

[filters.urlencode]
fn = "jinja2.filters.do_urlencode"
group = "builtin"
[filters.urlencode.examples.basic]
template = """
{{ "sth" | urlencode }}
"""

[filters.urlize]
fn = "jinja2.filters.do_urlize"
group = "builtin"
[filters.urlize.examples.basic]
template = """
{{ "sth" | urlize }}
"""

[filters.wordcount]
fn = "jinja2.filters.do_wordcount"
group = "builtin"
[filters.wordcount.examples.basic]
template = """
{{ "sth" | wordcount }}
"""

[filters.wordwrap]
fn = "jinja2.filters.do_wordwrap"
group = "builtin"
[filters.wordwrap.examples.basic]
template = """
{{ "sth" | wordwrap }}
"""

[filters.xmlattr]
fn = "jinja2.filters.do_xmlattr"
group = "builtin"
[filters.xmlattr.examples.basic]
template = """
{{ "sth" | xmlattr }}
"""

[filters.tojson]
fn = "jinja2.filters.do_tojson"
group = "builtin"
[filters.tojson.examples.basic]
template = """
{{ "sth" | tojson }}
"""

